{
 "title": "Cable Modem + Ping Status",
 "description": "Monitor FRITZ!Box DOCSIS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Kanal Modulation QAM (Senderichtung)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"up\" and\r\n                        r._field == \"Modulation\"\r\n            )\r\n  |> drop(columns: [\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kanal Modulation QAM (Empfangsrichtung)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"down\" and\r\n                        r._field == \"Modulation\"\r\n            )\r\n  |> drop(columns: [\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gesamt Modulation QAM (Senderichtung)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"up\" and\r\n                        r._field == \"Modulation\"\r\n            )\r\n  |> drop(columns: [\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\r\n  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gesamt Modulation QAM (Empfangsrichtung)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"down\" and\r\n                        r._field == \"Modulation\"\r\n            )\r\n  |> drop(columns: [\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ping\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    //r.host == \"193.168.248.1\" and\r\n    //r.name = \"gateway\" and\r\n    r._field == \"loss\"\r\n  )\r\n  |> aggregateWindow(every: \r\n      v.windowPeriod, fn: max)\r\n      //2m, fn: mean)\r\n      //2m, fn: mean)\r\n  "
    }
   ]
  },
  {
   "title": "Fehler (Empfangsrichtung)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "nicht korrigierbar",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \n                        r.mode == \"down\"\n            )\n  |> filter(fn: (r) => r._field == \"correctedErrors\")\n  |> drop(columns: [\"mode\",\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "param", "operator": "=", "value": "nicht korrigierbare Fehler" }
     ]
    },
    {
     "alias": "korrigierbar",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fritzbox",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"down\"\r\n            )\r\n  |> filter(fn: (r) => r._field == \"Errors\")\r\n  |> drop(columns: [\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "param", "operator": "=", "value": "korrigierbare Fehler" }
     ]
    }
   ]
  },
  {
   "title": "Power Level (Senderichtung)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "fritzbox",
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"up\"\r\n            )\r\n  |> filter(fn: (r) => r._field == \"PowerLevel\")\r\n  |> drop(columns: [\"_field\",\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "down" },
      { "condition": "AND", "key": "param", "operator": "=", "value": "Power Level [dBmV]" }
     ]
    }
   ]
  },
  {
   "title": "Power Level (Empfangsrichtung)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "fritzbox",
     "query": "// v.windowPeriod is a variable referring to the current optimized window period (currently: $interval)\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r._measurement == \"fritzbox\" and \r\n                        r.mode == \"down\"\r\n            )\r\n  |> filter(fn: (r) => r._field == \"PowerLevel\")\r\n  |> drop(columns: [\"_field\",\"mode\",\"_measurement\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "down" },
      { "condition": "AND", "key": "param", "operator": "=", "value": "Power Level [dBmV]" }
     ]
    }
   ]
  }
 ]
}